// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using AutoNomX.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoNomX.Infrastructure.Migrations
{
    [DbContext(typeof(AutoNomXDbContext))]
    [Migration("20260325180000_DropAgentMetricsForeignKey")]
    partial class DropAgentMetricsForeignKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Uses same model as snapshot (see AutoNomXDbContextModelSnapshot)
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
